"""Utility functions for bsaseq."""

from bsaseq.utils.errors import (
    BSASeqError,
    display_error,
    display_warning,
    format_file_not_found,
    format_insufficient_samples,
    format_invalid_parameter,
    format_missing_format_field,
    format_no_candidates_error,
    format_no_variants_error,
    format_output_error,
    format_sample_not_found,
    format_sample_overlap,
    format_snpeff_error,
)
from bsaseq.utils.logging import (
    create_progress,
    get_logger,
    log_error,
    log_info,
    log_step,
    log_success,
    log_warning,
    print_error,
    print_file_created,
    print_info,
    print_section,
    print_stats,
    print_success,
    print_warning,
    progress_iterator,
    setup_logging,
    track_progress,
)
from bsaseq.utils.sorting import (
    get_chromosome_order,
    natural_sort_key,
    simplify_chromosome_label,
    sort_chromosomes,
)
from bsaseq.utils.validation import (
    ValidationError,
    validate_output_path,
    validate_parameters,
    validate_samples,
    validate_vcf,
)

__all__ = [
    # Logging
    "create_progress",
    "get_logger",
    "log_error",
    "log_info",
    "log_step",
    "log_success",
    "log_warning",
    "print_error",
    "print_file_created",
    "print_info",
    "print_section",
    "print_stats",
    "print_success",
    "print_warning",
    "progress_iterator",
    "setup_logging",
    "track_progress",
    # Sorting
    "get_chromosome_order",
    "natural_sort_key",
    "simplify_chromosome_label",
    "sort_chromosomes",
    # Validation
    "ValidationError",
    "validate_output_path",
    "validate_parameters",
    "validate_samples",
    "validate_vcf",
    # Errors
    "BSASeqError",
    "display_error",
    "display_warning",
    "format_file_not_found",
    "format_invalid_parameter",
    "format_insufficient_samples",
    "format_missing_format_field",
    "format_no_candidates_error",
    "format_no_variants_error",
    "format_output_error",
    "format_sample_not_found",
    "format_sample_overlap",
    "format_snpeff_error",
]
